### ISSUE TITLE
Fix root README typos

### ISSUE THREAD

**Issue by c-guntur** [c-guntur/java-katas#10]
1. Fix the java-optionals to java-optional.
2. Fix the 'repacements' to 'replacements'

Run a spellcheck on the entire README, fix other typos.

**Comment by c-guntur** [comment]
Thank you @Bukama ! Please comment here, so I can assign this issue to you, before I close it.

**Comment by Bukama** [comment]
here 😇

**Comment by c-guntur** [comment]
Thanks to changes by @Bukama - this issue is resolved.
