### ISSUE TITLE
Rename tests in solutions and test directories for all katas

### ISSUE THREAD

**Issue by c-guntur** [c-guntur/java-katas#12]
Prefix all Kata tests with TestKata# (test number) and prefix all Solution tests with TestSolution#.

Replace current naming of Test#**Test and STest#**Test

**Comment by zhe1ezniak** [comment]
Can I take it?

**Comment by zhelezniak88** [comment]
Hello. Can I fix this issue?

**Comment by c-guntur** [comment]
Assigned to you now, @zhe1ezniak!

**Comment by zhelezniak88** [comment]
Hello. Thanx.
I found tests with naming S#**Test in the java-handles directory. Should I replace them?
