### ISSUE TITLE
Activate Travis CI integration

### ISSUE THREAD

**Issue by sormuras** [c-guntur/java-katas#2]
https://travis-ci.org/c-guntur/java-katas

**Comment by sormuras** [comment]
Do steps 1, 2, and 3 listed here: https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci

Step 4 and 5 are already done. Next commit should then trigger a CI build.

**Comment by sormuras** [comment]
@c-guntur Steps 1..3 are yours. Nobody else can help you with them. 😉

**Comment by c-guntur** [comment]
Thank you Christian ! Can we use travis-ci.org, not sure if the Pro version is needed for an open source non-commercial project.

**Comment by sormuras** [comment]
Sure. Works the same, afaik.

**Comment by sormuras** [comment]
Use: `[![Build Status](https://travis-ci.org/c-guntur/java-katas.svg?branch=master)](https://travis-ci.org/c-guntur/java-katas)`
Get: [![Build Status](https://travis-ci.org/c-guntur/java-katas.svg?branch=master)](https://travis-ci.org/c-guntur/java-katas)

**Comment by c-guntur** [comment]
Done ! Thanks !

**Comment by sormuras** [comment]
Awesome.
