### ISSUE TITLE
java-optional solutions not tested when mvn run from root

### ISSUE THREAD

**Issue by c-guntur** [c-guntur/java-katas#6]
Currently three katas exist. When running mvn clean install or mvn verify from the root, the JUnit tests under the **src/solutions/java** for **java-datetime** and **java-handles** are executed and test results produced. However, the JUnit tests under the **src/solutions/java** for **java-optionals** are not run. This needs to be fixed.

**Comment by c-guntur** [comment]
@zbytt - please comment here, so I can assign the ticket to you !

**Comment by c-guntur** [comment]
@sormuras - Will assign @zbytt to this ticket once they comment here. Requested a change to update the java-optional/README.md as well for this change on #9.

**Comment by c-guntur** [comment]
I was thinking of including an <includes> section in the root pom.xml that will allow us to bypass this duplicated 'Test' in the names. What are your thoughts?

            

```
               <plugin>

                    <groupId>org.apache.maven.plugins</groupId>

                    <artifactId>maven-surefire-plugin</artifactId>

                    <version>2.22.2</version>

                    <configuration>

                        <groups>PASSING</groups>

                        <excludedGroups>TODO</excludedGroups>

                        <includes>

                            <include>**/**Test**.java</include>

                        </includes>

                    </configuration>

                </plugin>

```

**Comment by sormuras** [comment]
I'd recommend to stay as close to defaults and best-practices as possible. If a user copies over test class to its own project, it should be included right away, i.e. there shouldn't be a need to configure any build tool.

Thus, any names that start with `Test` or end with `Test[s]` are my favorites.

**Comment by sormuras** [comment]
What about the following naming pattern?

- Kata: `TestKataXyz345.java`
- Solution: `TestSolutionXyz345.java`

**Comment by zbytt** [comment]
To be honest it is actually so uncommon for me to have a 'Test' at the beginning of a test class name that I did not even realize it is there.

I would  only leave 'Test' suffix really, but why not add 'Solution'  and 'Kata' as  include patterns  :)

**Comment by c-guntur** [comment]
Agree with both of you in terms of the naming. I can close this ticket out and open a new one to rename the tests and solutions. 

Prefix all Kata tests with TestKata# (test number) and prefix all Solution tests with TestSolution#.
